package Exception;

public class Arithmetic {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
try {
	int a=30/0;

}
catch(Exception e)
{
	System.out.println(e);
}
	}

}
